[
    {
        "Datayear": 2018,
        "ProvinceCD": 1,
        "Province": "WC",
        "Official_Institution_Name": "MBAO CENTER",
        "Status": "OPEN",
        "Sector": "INDEPENDENT",
        "Type_DoE": "Clinical",
        "Specialization": "Genaral",
        "OwnerLand": "Government",
        "OwnerBuildings": "Government",
        "GIS_Longitude": "18.489704",
        "GIS_Latitude": -33.940894,
        "LMunName": "CITY OF CAPE TOWN",
        "Suburb": "OBSERVATORY",
        "TownCity": "CITY OF CAPE TOWN",
        "StreetAddress": "Oude Molen Eco Village",
        "PostalAddress": "P.O. BOX 13416, MOWBRAY, 7705",
        "Section21": "YES",
    },
    {
        "Datayear": 2018,
        "ProvinceCD": 1,
        "Province": "WC",
        "Official_Institution_Name": "MBAO CENTER",
        "Status": "OPEN",
        "Sector": "INDEPENDENT",
        "Type_DoE": "Clinical",
        "Specialization": "Genaral",
        "OwnerLand": "Government",
        "OwnerBuildings": "Government",
        "GIS_Longitude": "18.489704",
        "GIS_Latitude": -33.940894,
        "LMunName": "CITY OF CAPE TOWN",
        "Suburb": "OBSERVATORY",
        "TownCity": "CITY OF CAPE TOWN",
        "StreetAddress": "Oude Molen Eco Village",
        "PostalAddress": "P.O. BOX 13416, MOWBRAY, 7705",
        "Section21": "YES",
    },
    {
        "Datayear": 2018,
        "ProvinceCD": 1,
        "Province": "WC",
        "Official_Institution_Name": "MBAO CENTER",
        "Status": "OPEN",
        "Sector": "INDEPENDENT",
        "Type_DoE": "Clinical",
        "Specialization": "Genaral",
        "OwnerLand": "Government",
        "OwnerBuildings": "Government",
        "GIS_Longitude": "18.489704",
        "GIS_Latitude": -33.940894,
        "LMunName": "CITY OF CAPE TOWN",
        "Suburb": "OBSERVATORY",
        "TownCity": "CITY OF CAPE TOWN",
        "StreetAddress": "Oude Molen Eco Village",
        "PostalAddress": "P.O. BOX 13416, MOWBRAY, 7705",
        "Section21": "YES",
    },
    {
        "Datayear": 2018,
        "ProvinceCD": 1,
        "Province": "WC",
        "Official_Institution_Name": "MBAO CENTER",
        "Status": "OPEN",
        "Sector": "INDEPENDENT",
        "Type_DoE": "Clinical",
        "Specialization": "Genaral",
        "OwnerLand": "Government",
        "OwnerBuildings": "Government",
        "GIS_Longitude": "18.489704",
        "GIS_Latitude": -33.940894,
        "LMunName": "CITY OF CAPE TOWN",
        "Suburb": "OBSERVATORY",
        "TownCity": "CITY OF CAPE TOWN",
        "StreetAddress": "Oude Molen Eco Village",
        "PostalAddress": "P.O. BOX 13416, MOWBRAY, 7705",
        "Section21": "YES",
    },
    {
        "Datayear": 2018,
        "ProvinceCD": 1,
        "Province": "WC",
        "Official_Institution_Name": "MBAO CENTER",
        "Status": "OPEN",
        "Sector": "INDEPENDENT",
        "Type_DoE": "Clinical",
        "Specialization": "Genaral",
        "OwnerLand": "Government",
        "OwnerBuildings": "Government",
        "GIS_Longitude": "18.489704",
        "GIS_Latitude": -33.940894,
        "LMunName": "CITY OF CAPE TOWN",
        "Suburb": "OBSERVATORY",
        "TownCity": "CITY OF CAPE TOWN",
        "StreetAddress": "Oude Molen Eco Village",
        "PostalAddress": "P.O. BOX 13416, MOWBRAY, 7705",
        "Section21": "YES",
    },
]